apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    env: test
spec:
  containers:
    - name: my-nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: 512Mi
          cpu: "0.5"
        requests:
          memory: 512Mi
          cpu: "0.3"
