apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: mypod2
  labels:
    name: mypod2
spec:
  containers:
  - name: mypod2
    image: nginx
    resources:
      requests: 
        cpu: "500m" 
        memory: "500Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}